# Generated by Django 3.2.7 on 2021-10-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='date and time of the last modification')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='date and time when create de job')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ('-date_created', '-date_modified'),
                'get_latest_by': 'date_created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='date and time of the last modification')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='date and time when create de job')),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('ranking', models.IntegerField(default=1)),
                ('skill', models.ManyToManyField(to='public_jobs.Skill')),
            ],
            options={
                'ordering': ('-date_created', '-date_modified'),
                'get_latest_by': 'date_created',
                'abstract': False,
            },
        ),
    ]
