# Generated by Django 3.2.7 on 2021-10-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='ranking',
        ),
        migrations.AddField(
            model_name='skill',
            name='ranking',
            field=models.IntegerField(default=1),
        ),
    ]
